INSERT INTO PRESUPUESTAR.BASIC_PROFILE
	( BASIC_PROFILE_ID, FIRST_NAME, LAST_NAME )
	VALUES ( 1, 'Sebastian', 'Lavie' );
INSERT INTO PRESUPUESTAR.PERSON 
	( PERSON_ID, EMAIL, PASSWORD, PROFILE_ID )
	VALUES ( 1, 'person@presupuestar.com', 'password', 1 );

INSERT INTO PRESUPUESTAR.CATEGORY
	( CATEGORY_ID, NAME )
	VALUES ( 1, 'Informatica / Sistemas' );
INSERT INTO PRESUPUESTAR.PROFESSION
	( PROFESSION_ID, NAME, CATEGORY_ID, LIST_INDEX )
	VALUES ( 1, 'Arquitecto de Software', 1, 0 );
INSERT INTO PRESUPUESTAR.PROFESSION
	( PROFESSION_ID, NAME, CATEGORY_ID, LIST_INDEX )
	VALUES ( 2, 'Desarrollador / Programador', 1, 1 );
INSERT INTO PRESUPUESTAR.PROFESSION
	( PROFESSION_ID, NAME, CATEGORY_ID, LIST_INDEX )
	VALUES ( 3, 'Analista de Negocios', 1, 2 );
INSERT INTO PRESUPUESTAR.FULL_PROFILE
	( FULL_PROFILE_ID, FIRST_NAME, LAST_NAME, REASON, WEB_PAGE )
	VALUES ( 1, 'Sebastian', 'Lavie', NULL, 'http://www.presupuestar.cl' );
INSERT INTO PRESUPUESTAR.PHONE
	( PHONE_ID, PHONE_NUMBER, PROFILE_ID, LIST_INDEX )
	VALUES ( 1, '+56 9 92584930', 1, 0 );
INSERT INTO PRESUPUESTAR.PHONE
	( PHONE_ID, PHONE_NUMBER, PROFILE_ID, LIST_INDEX )
	VALUES ( 2, '+54 9 2215388299', 1, 1 );
INSERT INTO PRESUPUESTAR.ADDRESS
	( ADDRESS_ID, ADDRESS_LINE_1, ADDRESS_LINE_2, ZIP_CODE, CITY, STATE, COUNTRY, PROFILE_ID, LIST_INDEX )
	VALUES ( 1, 'Av. Nueva Providencia 2170 #703', 'Providencia', '7500000', 'Santiago', 'RM', 'Chile', 1, 0 );
INSERT INTO PRESUPUESTAR.PROFESSIONAL 
	( PROFESSIONAL_ID, EMAIL, PASSWORD, PROFESSIONAL_TYPE, PROFESSION_ID, PROFILE_ID, AVG_SCORE )
	VALUES ( 1, 'professional@presupuestar.com', 'password', 'SELF_EMPLOYED', 1, 1, 9 );

INSERT INTO PRESUPUESTAR.STORE
	( STORE_ID, NAME )
	VALUES ( 1, 'My Web Store' );
INSERT INTO PRESUPUESTAR.PRODUCT
	( PRODUCT_ID, CODE, NAME, DESCRIPTION, PRICE, STORE_ID, LIST_INDEX )
	VALUES ( 1, '10000987543', 'Product 1', 'Description for the Product 1', 1500, 1, 0 );
INSERT INTO PRESUPUESTAR.PRODUCT
	( PRODUCT_ID, CODE, NAME, DESCRIPTION, PRICE, STORE_ID, LIST_INDEX )
	VALUES ( 2, '10000987555', 'Product 2', 'Description for the Product 2', 7500, 1, 1 );
	
INSERT INTO PRESUPUESTAR.FULL_PROFILE
	( FULL_PROFILE_ID, FIRST_NAME, LAST_NAME, REASON, WEB_PAGE )
	VALUES ( 2, NULL, NULL, 'My Commerce Name', 'http://www.presupuestar.cl' );
INSERT INTO PRESUPUESTAR.PHONE
	( PHONE_ID, PHONE_NUMBER, PROFILE_ID, LIST_INDEX )
	VALUES ( 3, '+56 9 224255251', 2, 0 );
INSERT INTO PRESUPUESTAR.ADDRESS
	( ADDRESS_ID, ADDRESS_LINE_1, ADDRESS_LINE_2, ZIP_CODE, CITY, STATE, COUNTRY, PROFILE_ID, LIST_INDEX )
	VALUES ( 2, 'Av. Nueva Providencia 2170 #703', 'Providencia', '7500000', 'Santiago', 'RM', 'Chile', 2, 0 );
INSERT INTO PRESUPUESTAR.COMMERCE 
	( COMMERCE_ID, EMAIL, PASSWORD, STORE_ID, PROFILE_ID, AVG_SCORE )
	VALUES ( 1, 'commerce@presupuestar.com', 'password', 1, 2, 8 );

INSERT INTO PRESUPUESTAR.PRODUCTS_BUDGET 
	( PRODUCTS_BUDGET_ID, AMOUNT, COMMERCE_ID, COMMERCE_ID2, COMM_BUDGET_IDX )
	VALUES ( 1, 4000, 1, 1, 0 );

INSERT INTO PRESUPUESTAR.PRODUCTS_DETAIL
	( PRODUCTS_DETAIL_ID, DESCRIPTION, AMOUNT )
	VALUES ( 1, 'Description for Product Detail 1', 4000 );
INSERT INTO PRESUPUESTAR.ITEM 
	( ITEM_ID, NAME, PRICE, QUANTITY, PRODUCTS_DETAIL_ID, PRODUCTS_DETAIL_ITEM_IDX )
	VALUES ( 1, 'Item 1 - No Product', 1000, 1, 1, 0 );
INSERT INTO PRESUPUESTAR.ITEM_BUDGET 
	( ITEM_BUDGET_ID, AMOUNT, PRODUCTS_BUDGET_ID, ITEM_ID, PRODUCT_ID, PRODBGT_ITEM_IDX )
	VALUES ( 1, 1000, 1, 1, NULL, 0 );
INSERT INTO PRESUPUESTAR.ITEM 
	( ITEM_ID, NAME, PRICE, QUANTITY, PRODUCTS_DETAIL_ID, PRODUCTS_DETAIL_ITEM_IDX )
	VALUES ( 2, 'Item 2 - Product 1', 1500, 2, 1, 1 );
INSERT INTO PRESUPUESTAR.ITEM_BUDGET 
	( ITEM_BUDGET_ID, AMOUNT, PRODUCTS_BUDGET_ID, ITEM_ID, PRODUCT_ID, PRODBGT_ITEM_IDX )
	VALUES ( 2, 3000, 1, 2, 1, 1 );
	
INSERT INTO PRESUPUESTAR.LABOR_DETAIL 
	( LABOR_DETAIL_ID, DESCRIPTION, AMOUNT )
	VALUES ( 1, 'Description for Labor Detail 1', 10000 );
INSERT INTO PRESUPUESTAR.LABOR_BUDGET 
	( LABOR_BUDGET_ID, AMOUNT, PROFESSIONAL_ID, LABOR_DETAIL_ID, PRODUCTS_DETAIL_ID, PROFESSIONAL_ID2, PROF_BUDGET_IDX )
	VALUES ( 1, 14000, 1, 1, 1, 1, 0 );

INSERT INTO PRESUPUESTAR.BUDGET 
	( BUDGET_ID, AMOUNT, LABOR_BUDGET_ID, PRODUCTS_BUDGET_ID, AVG_SCORE )
	VALUES ( 1, 14000, 1, 1, 7 );

INSERT INTO PRESUPUESTAR.FEEDBACK 
	( FEEDBACK_ID, FEEDBACK_TYPE, SCORE, FEEDBACK_ON_CLASS, FEEDBACK_ON_ID, PROFESSIONAL_ID, PROF_FBK_IDX, COMMERCE_ID, COMM_FBK_IDX, BUDGET_ID, BGT_FBK_IDX )
	VALUES ( 1, 'ON_USER', 7, 'BUDGET', 1, NULL, NULL, NULL, NULL, 1, 0 );
INSERT INTO PRESUPUESTAR.FEEDBACK 
	( FEEDBACK_ID, FEEDBACK_TYPE, SCORE, FEEDBACK_ON_CLASS, FEEDBACK_ON_ID, PROFESSIONAL_ID, PROF_FBK_IDX, COMMERCE_ID, COMM_FBK_IDX, BUDGET_ID, BGT_FBK_IDX )
	VALUES ( 2, 'ON_USER', 8, 'COMMERCE', 1, 1, 0, NULL, NULL, NULL, NULL );
INSERT INTO PRESUPUESTAR.FEEDBACK 
	( FEEDBACK_ID, FEEDBACK_TYPE, SCORE, FEEDBACK_ON_CLASS, FEEDBACK_ON_ID, PROFESSIONAL_ID, PROF_FBK_IDX, COMMERCE_ID, COMM_FBK_IDX, BUDGET_ID, BGT_FBK_IDX )
	VALUES ( 3, 'ON_USER', 9, 'PROFESSIONAL', 1, NULL, NULL, 1, 0, NULL, NULL );

INSERT INTO PRESUPUESTAR.COMMENT 
	( COMMENT_ID, COMMENT, COMMENT_DATE, AUTHOR_CLASS, AUTHOR_ID, FEEDBACK_ID, FBK_COMMENT_IDX )
	VALUES ( 1, 'Comment on Feedback 1', '2013-11-23', 'PERSON', 1, 1, 0 );
INSERT INTO PRESUPUESTAR.COMMENT 
	( COMMENT_ID, COMMENT, COMMENT_DATE, AUTHOR_CLASS, AUTHOR_ID, FEEDBACK_ID, FBK_COMMENT_IDX )
	VALUES ( 2, '1st Comment on Feedback 1', '2013-11-23', 'PERSON', 1, 2, 0 );
INSERT INTO PRESUPUESTAR.COMMENT 
	( COMMENT_ID, COMMENT, COMMENT_DATE, AUTHOR_CLASS, AUTHOR_ID, FEEDBACK_ID, FBK_COMMENT_IDX )
	VALUES ( 3, '2nd Comment on Feedback 2', '2013-11-23', 'PROFESSIONAL', 1, 2, 1 );
INSERT INTO PRESUPUESTAR.COMMENT 
	( COMMENT_ID, COMMENT, COMMENT_DATE, AUTHOR_CLASS, AUTHOR_ID, FEEDBACK_ID, FBK_COMMENT_IDX )
	VALUES ( 4, 'Comment on Feedback 3', '2013-11-23', 'COMMERCE', 1, 3, 0 );
